### ISSUE TITLE
Device not connected in Docker installation

### ISSUE THREAD

**Issue by mauroreggio** [vitalidze/traccar-web#1238]
Hi, thanks for reply in advice.
I try install in a couple of server the Docker version (a couple of server for test if first time something go wrong). In any installation i have the same issue. 
I add the device (traccar client on iPhone or Android phone) on web interface where i can login correctly. After that i configure the client to send position to the IP of server and port 8082 (the only port opened from docker-compose).
On the client, in the status page, not recognize any error, is like it send correctly data to the server (if i change address and put something wrong, i recognize "Send Error"). But on server side i not can see any logs of the arrive data (./logs/tracker-server.log) and i not can see the device on the web interface.
Anyone have my same issue?
Thanks.

**Comment by mauroreggio** [comment]
Sorry, i find my reply alone.
For anyone other that have the same issue: 
- you must edit and add the port 5055 redirection to the docker-compose,yml file for expose 5055 port too (watch at the last line)
- the client device must be configured for send data to the 5055 port, not to the 8082 (that i think is onlly for the web interface).

```
version: "2"
services:
  traccar:
    image: vitalidze/traccar-web:0.12.3-h2
    container_name: traccar-web
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    volumes:
      - ./logs:/opt/traccar/logs
      - ./data:/opt/traccar/data
    ports:
      - "8082:8082"
      - "5055:5055"
```
